### ISSUE TITLE
Ошибка при импорте

### ISSUE THREAD

**Issue by glebliutsko** [nalgeon/iuliia-py#2]
При попытке импортировать пакет прилетает исключение `AttributeError: ala_lc`.

```python
>>> import iuliia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/gittmp_gleb/tmp.yZ1EPjt5eG_105510_/iuliia/__init__.py", line 13, in <module>
    ALA_LC = Schemas.ala_lc.value  # type: ignore
  File "/usr/lib/python3.8/enum.py", line 341, in __getattr__
    raise AttributeError(name) from None
AttributeError: ala_lc
```

```bash
$ python --version
Python 3.8.3
$ uname -a
Linux GlebPC 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64 GNU/Linux
```

**Comment by nalgeon** [comment]
Не воспроизводится. Почему у вас идёт импорт из `/tmp/gittmp_gleb`, как устанавливали пакет?
